include:
  - local: .gitlab/.pipeline-template.yml
  - local: .gitlab/.pipeline-environment.yml

stages: [test, build, deploy]

workflow:
  auto_cancel:
    on_new_commit: interruptible

prepare dependencies:
  stage: .pre
  image: node:20.9.0
  interruptible: true
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test lint:
  stage: test
  image: node:20.9.0
  interruptible: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run lint
    - npm run build

unit test:
  stage: test
  image: node:20.9.0
  interruptible: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm test auth # <=== Chỉ chạy test cho module auth do các module khác chưa có test

e2e test:
  stage: test
  image: node:20.9.0
  interruptible: true
  script:
    - echo "E2E test running"

build docker:
  stage: build
  image: docker:git
  interruptible: true
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo $CI_COMMIT_REF_SLUG # <=== Dùng để in
    - echo $CI_COMMIT_BRANCH # <=== Dùng để in ra tên branch
    - echo $CI_DEFAULT_BRANCH # <=== Dùng để in ra tên branch mặc định
    - | # <=== Dùng cho các script xuống hàng
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^deploy\/.*$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - changes:
        - Dockerfile
        - package-lock.json
        - package.json
        - src/**/*
        - .env
        - nest-cli.json
# deploy staging:
#   stage: deploy
#   script:
#     - echo "Deploy to staging server"
#   only:
#     - deploy/staging

deploy staging:
  extends: .deploy
  variables: !reference [.staging, variables]
  rules:
    - !reference [.staging, rules]
deploy uat:
  extends: .deploy
  variables: !reference [.uat, variables]
  rules:
    - !reference [.staging, rules]
