stages: [test, build, deploy]

test lint:
  stage: test
  image: node:20.9.0
  script:
    - npm install
    - npm run lint
    - npm run build

unit test:
  stage: test
  image: node:20.9.0
  script:
    - npm install
    - npm test auth # <=== Chỉ chạy test cho module auth do các module khác chưa có test

integration test:
  stage: test
  image: node:20.9.0
  script:
    - echo "Integration test running"

build docker:
  stage: build
  image: docker:git
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo $CI_COMMIT_REF_SLUG # <=== Dùng để in
    - echo $CI_COMMIT_BRANCH # <=== Dùng để in ra tên branch
    - echo $CI_DEFAULT_BRANCH # <=== Dùng để in ra tên branch mặc định
    - | # <=== Dùng cho các script xuống hàng
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

deploy staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  only:
    - deploy/staging
